version: '3'

services:
  malexer-twemproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: malexer/twemproxy:0.5.0
    container_name: malexer-twemproxy
    environment:
      REDIS_SERVERS: "172.18.0.1:6379:1,172.18.0.1:6379:2,172.18.0.1:6379:3"
    ports:
      - 6380:6380
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
